# Generated by Django 5.2.4 on 2025-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
